myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.


class MainImage(models.Model):
    name = models.CharField(max_length=10)
    main_image=  models.ImageField()
    
    def __str__ (self):
        return self.name
    
    
class SecondImage(models.Model):
    name= models.CharField(max_length=10)
    firt_image = models.ImageField()
    second_image = models.ImageField()
    third_image = models.ImageField()
    
    def __str__ (self):
        return self.name
    
    
class ThirdImage(models.Model):
    name = models.CharField(max_length=10)
    about_image = models.ImageField()
    
    def __str__ (self):
        return self.name

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . models import MainImage, SecondImage, ThirdImage
from django.contrib import messages

# Create your views here.

def index(request):
    firstimage = MainImage.objects.all()
    secondsection = SecondImage.objects.all()
    thirdsection = ThirdImage.objects.all()
    return render(request, 'core/index.html', {'firstimage':firstimage, 'secondsection':secondsection, 'thirdsection':thirdsection})


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        
        myuser = User.objects.create_user(username, email, password1)
        myuser.first_name = firstname
        myuser.last_name = lastname
        
        myuser.save()
        messages.success(request, ('You are successfully registered!'))
        return redirect('/')
    return render(request, 'core/signup.html', )

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        
        user = authenticate(username=username, password=password1)
        
        if user is not None:
            login(request, user)
            messages.success(request, 'You are successfully logged in!')
            
            return redirect('/')
        
        
    return render(request, 'core/login.html')

def signout(request):
    logout(request)
    messages.success(request, 'You are successfully logged out!')
    return redirect('myapp:index')

myapp/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>
<body>
   
  <nav  class="navbar navbar-dark  fixed-top" style="background-color: #1e3956;">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 px-3" href="#">ISLMbymore</a>
      <div class="nav d-flex gap-4" >
      <ul>
        <li class="link"><a href="{% url 'myapp:index' %}">Home</a></li>
        <li class="link"><a href="#about">About</a></li>
        <li class="link"><a href="#contact">Contact</a></li>
        {% if user.is_authenticated %}
        <li class="link"><a href="{% url 'myapp:signout' %}" class="btn btn-danger">Sign out</a></li>
        {% else %}
        <li class="link"><a href="{% url 'myapp:signin' %}" class="btn btn-primary">Sign in</a></li>
        <li class="link"><a href="{% url 'myapp:signup' %}" class="btn btn-success">Sign up</a></li>
        {% endif %}
      </ul>


    </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="offcanvas offcanvas-end " tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel" style="background-color: #1e3956;">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title text-light" id="offcanvasDarkNavbarLabel">ISLMbymore</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body " style="background-color: #1e3956;">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <li class="py-2"><a href="{% url 'myapp:index'%}">Home</a></li>
              <li class="py-2"><a href="#about">About</a></li>
              <li class="py-2"><a href="#contact">Contact</a></li>
              <li class="py-2"><a href="" class="btn btn-primary">Sign in</a></li>
              <li class="py-2"><a href="{% url 'myapp:signup' %}" class="btn btn-success">Sign up</a></li>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex mt-3" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </nav>
  {% if messages %}
  <div class="py-5 px-5" style="background-color: #121f2d;">
    {% for message in messages %}
    <div style="margin: 70px 0; background-color: #1e3956;" class="py-4  rounded" >
    <p class="fw-semibold text-light">{{message}}</p>
    </div>
    {% endfor %}
  </div>
  {% endif %}
      {% block content %}

      {% endblock %}
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/core/login.html
{% extends 'core/base.html'%}

{% block title %} Sign in {% endblock %}

{% block content%}
<main class="signin py-5 mt-5 rounded" style="background-color: #121f2d;">
    <h1 class="text-center py-4 text-light" >Signin</h1>
    <div style="display: flex; justify-content: center;" class="signin">
        <form action="." method="post" style="display: grid; grid-template-columns: auto ; ">
            {% csrf_token %}
            <input class="form-control py-2 px-5" type="text" name="username" id="username" placeholder="Create Username"
                required>
            <br>
          
          
         
            <input class="form-control py-2 px-5" type="password" name="password1" id="password1" placeholder="Create password"
                required>
            <br>
          
            <button class="btn btn-success  py-3 px-4"><a class="text-decoration-none text-light"
                    href="">Submit</a></button>
        </form>
    </div>
    </main>
{% endblock %}

myapp/templates/core/signup.html
{% extends 'core/base.html' %}

{% block content %}
    <main class="signup py-5 mt-5">
            <h1 class="py-4">Sign up Page</h1>

        <div style="display: flex; justify-content: center;">
            <form action="." method="post" style="display: grid; grid-template-columns: auto ; ">
                {% csrf_token %}
                <input class="form-control py-2 px-5" type="text" name="username" id="username" placeholder="Create Username"
                    required>
                <br>
                <input class="form-control py-2 px-5" type="text" name="firstname" id="firstname" placeholder="Create firstname"
                    required>
                <br>
                <input class="form-control py-2 px-5" type="text" name="lastname" id="lastname" placeholder="Create lastname"
                    required>
                <br>
                <input class="form-control py-2 px-5" type="email" name="email" id="email" placeholder="Create email" required>
                <br>
                <input class="form-control py-2 px-5" type="password" name="password1" id="password1" placeholder="Create password"
                    required>
                <br>
                 <input class="form-control py-2 px-5" type="password" name="password2" id="password2" placeholder="Confirm password"
                    required>
                <br>
                <button class="btn btn-success  py-3 px-4"><a class="text-decoration-none text-light"
                        href="">Submit</a></button>
            </form>
        </div>
    </main>

{% endblock %}